[env]
_.python.venv = { path = ".venv", create = true }
JUST_UNSTABLE = "1"

[settings]
experimental = true
pipx_uvx = true
python.uv_venv_auto = true

[tools]
python = "3.14.2" # Required for documentation generation
rust = "1.91.1" # Required for schematools
"aqua:astral-sh/uv" = "0.9.15"
"aqua:casey/just" = "1.43.1"
"aqua:google/yamlfmt" = "0.20.0"
"aqua:helm" = "3.19.2"
"aqua:helm/chart-testing" = "3.14.0"
"aqua:mikefarah/yq" = "4.49.2"
"cargo:schematools-cli" = "0.22.0"
"pipx:yamllint" = "1.37.1"
"pipx:yamale" = "6.1.0"

[hooks]
postinstall = "uv pip install --upgrade -r {{config_root}}/docs/requirements.txt"
