[env]
_.python.venv = { path = ".venv", create = true }
JUST_UNSTABLE = "1"

[settings]
experimental = true
pipx_uvx = true
python.uv_venv_auto = true

[tools]
python = "3.14.3" # Required for documentation generation
rust = "1.93.1" # Required for schematools
k3d = "5.8.3"
"aqua:astral-sh/uv" = "0.10.3"
"aqua:casey/just" = "1.46.0"
"aqua:google/yamlfmt" = "0.21.0"
"aqua:helm" = "4.1.1"
"aqua:helm/chart-testing" = "3.14.0"
"aqua:mikefarah/yq" = "4.52.4"
"cargo:schematools-cli" = "0.22.0"
"pipx:yamllint" = "1.38.0"
"pipx:yamale" = "6.1.0"

[hooks]
postinstall = "uv pip install --upgrade -r {{config_root}}/docs/requirements.txt"
