---
apiVersion: v2
description: A Helm chart for the Multus CNI CustomResourceDefinition
name: multus
version: 1.2.0
appVersion: 4.2.4
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
sources:
  - https://github.com/k8snetworkplumbingwg/multus-cni
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |-
        Update multus-cni to v4.2.4
