---
apiVersion: v2
description: A Helm chart for the Multus CNI CustomResourceDefinition
name: multus
version: 1.1.2
appVersion: 4.2.2
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
sources:
  - https://github.com/k8snetworkplumbingwg/multus-cni
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |-
        Update common library to v4.6.1
