---
cni-plugins:
  image:
    repository: ghcr.io/home-operations/cni-plugins
    tag: 1.9.0
  resources: {}

multus:
  image:
    repository: ghcr.io/k8snetworkplumbingwg/multus-cni
    tag: v4.2.4
  resources: {}

cni:
  netPath: /etc/cni/net.d
  binPath: /opt/cni/bin
