---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 4.6.2
kubeVersion: ">=1.28.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s-labs/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
sources:
  - https://github.com/bjw-s-labs/helm-charts
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: |-
        Make port selection by identifier in backendRefs of HTTPRoute actually do something.
    - kind: fixed
      description: |-
        Route port was no longer optional while it should be.
